site_name: DAppNode Docs
theme: readthedocs
nav:
  - Home: index.md
  - Introduction: introduction.md
  - Install: install.md
  - Connect to DAppNode: connect.md
  - What can you do with DAppNode?: what-can-you-do.md
  - User Guide: user-guide.md
  - FAQs: faqs.md
  - Troubleshooting: troubleshooting.md
  - Architecture: architecture.md
  - Core packages readmes: Core-packages-readmes.md
  - Contributing: contributing.md
  - License: license.md

