# Customize left navigation menu
nav:
  - Home: index.md
  - Versions covered: versions.md
  - Introduction: introduction.md
  - Install: install.md
  - Connect to DAppNode: connect.md
  - What can you do with DAppNode?: what-can-you-do.md
  - User Guide: user-guide.md
  - FAQs: faqs.md
  - Troubleshooting: troubleshooting.md
  - Migration to v0.2.0: Migration to v0.2.0.md
  - Architecture: architecture.md
  - DAppNode Package Manifest Reference: manifest-reference.md
  - DAppNode Package Setup Wizard Reference: setup-wizard-reference.md
  - Core packages readmes: Core-packages-readmes.md
  - Contributing: contributing.md
  - License: license.md

# Configuration
site_name: Documentation
theme:
  name: "material"
  logo: "images/logo_with_name.png"
  favicon: "images/favicon.ico"
markdown_extensions:
  - codehilite
  - admonition
extra_css:
  - "stylesheets/extras.css"
extra:
  social:
    - type: "github"
      link: "https://github.com/dappnode/DAppNode"
    - type: "twitter"
      link: "https://twitter.com/dappnode"
    - type: "comments"
      link: "https://discourse.dappnode.io/"
    - type: "medium"
      link: "https://medium.com/dappnode"
