# Project information
site_name: DAppNode Docs

# Customize left navigation menu
nav:
  - Home: index.md
  - Introduction: introduction.md
  - Install: install.md
  - Connect to DAppNode: connect.md
  - What can you do with DAppNode?: what-can-you-do.md
  - User Guide: user-guide.md
  - DNP Manifest Reference: manifest-reference.md
  - FAQs: faqs.md
  - Troubleshooting: troubleshooting.md
  - Migration to v0.2.0: Migration to v0.2.0.md
  - Architecture: architecture.md
  - Core packages readmes: Core-packages-readmes.md
  - Contributing: contributing.md
  - License: license.md

# Configuration
theme:
  name: "material"
  favicon: "/img/favicon.ico"
markdown_extensions:
  - codehilite
  - admonition
extra:
  social:
    - type: "github"
      link: "https://github.com/dappnode/DAppNode"
    - type: "twitter"
      link: "https://twitter.com/dappnode"
